### ISSUE TITLE
Launch server programmatically?

### ISSUE THREAD

**Issue by connercowling** [jupyter/jupyter_server#10]
Is there a way to import notebook server into another module and start programmatically (as opposed to calling `jupyter notebook` with subprocess or something)?

I probably overlooked something, but I didn't see `notebook` exported in `__init__.py`, or any other avenue.

Thanks.

**Comment by takluyver** [comment]
Running it in a subprocess is generally the recommended way. If you really need to launch it in-process for some reason, `notebook.notebookapp.main()` should be the function you need to call.
