### ISSUE TITLE
Concurrent file serving is broken?

### ISSUE THREAD

**Issue by ebraminio** [jupyter/jupyter_server#11]
Hey guys, I am experiencing very weird issue with jupyter, that I guess is a regression, here is its steps to reproduce:

Create a notebook, put this code on first cell to create test images:

```python
from PIL import Image
from PIL import ImageDraw

for i in range(1, 6):
    img = Image.new('RGBA', (10, 10), 255)
    draw = ImageDraw.Draw(img)
    draw.text((0, 0), str(i), fill="black")
    img.save(str(i) + '.png')
```

Put this on the next cell as markdown:

```html
<img src="1.png" width="30">
<img src="2.png" width="30">
<img src="3.png" width="30">
<img src="4.png" width="30">
<img src="5.png" width="30">
<img src="6.png" width="30">
```

Actual:
I see such result this, differently every time:

![screen shot 2017-10-08 at 4 59 12 pm](https://user-images.githubusercontent.com/833473/31317232-14f7693c-ac4a-11e7-825d-405d619ebbd8.png)

Expected:
To images loaded correctly.

My system:
jupyter --version: 4.3.0
macOS High Sierra

I can reproduce this very consistently on my setup, Is jupyter server somehow fails on serving concurrent requests or something else is wrong?

**Comment by takluyver** [comment]
:confused: What do you see in the terminal where the notebook is running when you do that?

**Comment by takluyver** [comment]
Closing this one, let's continue on jupyter/jupyter#292.
