### ISSUE TITLE
Jupyter Server weekly meetings

### ISSUE THREAD

**Issue by Zsailer** [jupyter/jupyter_server#111]
I'd like to propose a weekly meeting for Jupyter Server so we can synchronize and catalyze development. I'm posting this issue here to gauge interest. I'll follow up over email.

I propose Thursday's at 8AM Pacific (your [timezone](https://arewemeetingyet.com/Los%20Angeles/2019-10-10/08:00/w/Jupyter%20Server%20Meeting)). 

The first meeting wouldn't be until next week, October 10th. If this time doesn't work for most people, I'm flexible to adjust. 

@kevin-bates @SylvainCorlay @maartenbreddels @blink1073 @echarles @jasongrout @ellisonbg @takluyver @minrk @vidartf @rgbkrk @mpacer @willingc @captainsafia @betatim @fperez

**Comment by blink1073** [comment]
:+1:

**Comment by ellisonbg** [comment]
👍

**Comment by willingc** [comment]
@rgbkrk @captainsafia fyi

Probably makes sense to give the Jupyter Steering Council a heads up on this meeting.

**Comment by willingc** [comment]
@ellisonbg @fperez Would it be possible to have a weekly standing meeting calendar published somewhere?

**Comment by SylvainCorlay** [comment]
@willingc just like jupyterhub has a team compass (https://jupyterhub-team-compass.readthedocs.io/en/latest/meetings.html) and voila has another published calendar (https://voila-dashboards.github.io/), I suggested consolidating all the public meetings in one display on https://jupyter.org/community

I am happy to make the change to the website, but super busy today.

**Comment by SylvainCorlay** [comment]
👍 on the meeting.

**Comment by willingc** [comment]
@SylvainCorlay Thanks. That would be a great first start.

**Comment by Zsailer** [comment]
Thanks @willingc! 

Also forgot @rolweber!

**Comment by kevin-bates** [comment]
@lresende may be interested as well.

**Comment by Zsailer** [comment]
Would someone on the steering council be willing to share this meeting with the rest of the SC? 😃 I don't know how to email the whole group directly. 

I wasn't expecting this much interest 😆 Thank you, everyone, for responding quickly. We'll have our first meeting (next) Thursday, October 10th. Let's meet on the [Cal Poly Zoom](https://calpoly.zoom.us/my/jupyter).

See you all there!

**Comment by rgbkrk** [comment]
I can make 8 am. I'll stick it on the calendar.

**Comment by captainsafia** [comment]
Works for me! See you next week.

**Comment by mpacer** [comment]
I'll put it on my calendar as well!

**Comment by Zsailer** [comment]
Hi all, 

Just a reminder that we're meeting tomorrow, 8AM Pacific (or your [timezone](https://arewemeetingyet.com/Los%20Angeles/2019-10-10/08:00/w/Jupyter%20Server%20Meeting)).

* We'll meet on [Cal Poly Zoom](https://calpoly.zoom.us/my/jupyter).
* Here is a [HackMD agenda](https://hackmd.io/Wmz_wjrLRHuUbgWphjwRWw?both) I made.

I'm moderate discussion and offer some recent background around the project.

I look forward to seeing y'all there! 😎

**Comment by echarles** [comment]
@Zsailer Will there be a follow-up meeting this week? I realise we did not take time (it was not at the agenda anyway) to validate the weekly cadence. Whatever planning it is, it would be good to be posted to book our calendar.

**Comment by Zsailer** [comment]
:+1: Yes, I'll be hosting these meetings weekly at the same time. Thursdays at 8am, pacific.

**Comment by vidartf** [comment]
Has this weeks meeting been yet? I feel like I might have gotten confused by the DST/timezones.

**Comment by echarles** [comment]
@vidartf We have just finished. So now you have the same feeling as I had yesterday for the jlab meeting :)

**Comment by Zsailer** [comment]
Hi all, 

I will be traveling during this week's (11/14) meeting time, so I won't be able to lead the meeting. I propose that we cancel this week's meeting, unless someone else would like to lead the call.

**Comment by ellisonbg** [comment]
Thanks, Zach - save travels...

On Wed, Nov 13, 2019 at 8:56 AM Zachary Sailer <notifications@github.com> wrote:
>
> Hi all,
>
> I will be traveling during this week's (11/14) meeting time, so I won't be able to lead the meeting. I propose that we cancel this week's meeting, unless someone else would like to lead the call.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Brian E. Granger

Principal Technical Program Manager, AWS AI Platform (brgrange@amazon.com)
On Leave - Professor of Physics and Data Science, Cal Poly
@ellisonbg on GitHub

**Comment by Zsailer** [comment]
closing this issue since we have a weekly meeting issue already.
