### ISSUE TITLE
Enable ExtensionApp to open/close browser

### ISSUE THREAD

**Issue by Zsailer** [jupyter/jupyter_server#120]
This line should be configured by the ExtensionApp. 

https://github.com/jupyter/jupyter_server/blob/4e6d9a06f2c2be64e6c98abd7f29b2bace650f55/jupyter_server/extension/application.py#L300

We should add an `open_browser` trait to the ExtensionApp and allow extensions to configure the server's trait here. 

@maartenbreddels

**Comment by vidartf** [comment]
Just to make it clear exactly what this issue is about: Do you have an expected/actual behavior pattern to share?

**Comment by Zsailer** [comment]
Solved in #128.
