### ISSUE TITLE
Refactor tests to use pytest fixtures

### ISSUE THREAD

**Issue by Zsailer** [jupyter/jupyter_server#136]
At the last jupyter_server meeting, I mentioned that Jupyter Server's testing framework needs some attention. It's fairly brittle and hasn't been reviewed since we forked from jupyter/notebook.

I argued that we should refactor the tests into pytest's fixture based style. I believe this is more readable and accessible to contributors. 

I think it's critical that we get our tests in place ASAP, so that development can move forward confidently. I'm going to spend some time this week refactoring tests.

**Comment by Zsailer** [comment]
Sharing an update here. 

I have a [separate repo](https://github.com/Zsailer/jupyter_server_tests) with pytests for Jupyter Server. Feel free to tour that repo while I continue working.

These tests rely on [pytest-tornado](https://github.com/eugeniy/pytest-tornado) and [pytest-asyncio](https://github.com/pytest-dev/pytest-asyncio). Getting these two libraries to work together took me more time than I'd like to admit... but I think the result is fantastic. 

* Tests are explicit. 
* They use the `async`/`await` syntax. 
* The fixtures are straightforward. 

The outcome is that tests should be easier to contribute to. I'll add a bit more documentation before moving the test modules over here.

I've also been using Github actions for deploying tests. I love it. I think we should consider moving our tests to Github actions from travis + appveyor. Thoughts?

**Comment by maartenbreddels** [comment]
> Getting these two libraries to work together took me more time than I'd like to admit...

I am not surprised, it's a tricky business, but very important work to get readable tests!




> but I think the result is fantastic.

🎉 

> I think we should consider moving our tests to Github actions from travis + appveyor. Thoughts?

What I've seen, it's pretty fast, so I'm all for it!

Thanks for spearheading this.

**Comment by Zsailer** [comment]
This is finally finished in #152 and #156!
