### ISSUE TITLE
Release jupyter_server 2.0.0 with kernel_mgmt 0.5.0

### ISSUE THREAD

**Issue by echarles** [jupyter/jupyter_server#138]
This issue is created to track the release of jupyter_server 0.2.0 with kernel_mgmt 0.5.0.

See also https://github.com/jupyter/jupyter_server/issues/127

**Comment by echarles** [comment]
See also https://github.com/takluyver/jupyter_kernel_mgmt/issues/33

**Comment by echarles** [comment]
jupyter_kernel_mgmt 0.5.0 has [just been released](https://github.com/takluyver/jupyter_kernel_mgmt/issues/33). It does not run on python 3.5.

I have opened https://github.com/jupyter/jupyter_server/pull/142 to enforce 3.6

**Comment by echarles** [comment]
Bases on the last commits, we should imho release a 0.3.0 asap based on master which delivers the mixin... and leave the 0.2 without the mixin.

The kernel mgmt can be released in a next 0.4.0.

WDYT @Zsailer @kevin-bates

**Comment by kevin-bates** [comment]
I'm okay with this.  I just have no cycles to help out right now - I'm sorry

**Comment by echarles** [comment]
Kernel Provider/Mgmt will not release. Closing,.
