### ISSUE TITLE
What to do with classic HTML templates

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/jupyter_server#16]
We have kept the HTML templates from the classic notebook server.

I guess that `404.html` and `error.html` and their bases belong to the server. What about the other ones?

**Comment by minrk** [comment]
Most should probably go away. 404/error rely on `page.html` for the basic layout. This is really part of the notebook application, though, not necessarily shared by everything.

An argument could be made that the pure server doesn't have pages, even errors, and those are provided by extensions, and the default server should have only super-minimal error pages by default.

**Comment by Zsailer** [comment]
We removed most of the templates in #54. We've included a minimal error page and main landing page for the server.

The main question I have is, what do we do with templates+handlers for terminals, nbconvert, editor, etc.? The notebook client includes templates, js, and css for these APIs, but the server includes the backend APIs. Should we always require that extensions provide their own frontend to these APIs?

**Comment by Zsailer** [comment]
This might indicate that those APIs should be made into server extensions and remain separate from the server. The server only comes with the pieces in the `services` submodule.

**Comment by vidartf** [comment]
I see that the login/logout templates were removed, but the corresponding handlers are still a part of the server. What is the intended way of operation here? The auth logic should ideally be shared between different Jupyter apps on the same system, so I would argue for keeping some sane minimum implementation. Alternatively, I would prefer to keep at least an extensible template base.

**Comment by Zsailer** [comment]
@vidartf, I agree. I actually opened an #85 to discuss this. Closing this issue in favor of #85 to focus discussion on login/logout.
