### ISSUE TITLE
Filtering kernel messages

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/jupyter_server#17]
One of the goals of the standalone `jupyters_server` is to enable use cases where certain messages are not allowed such as `execute_requests`.

The main usecase is for widgets-based applications, that should not allow arbitrary code execution.

Should there be an option for disabling execute_request globally (at least as a first iteration), or have a more complex security scenario where this would depend on who is connected.

cc @jasongrout @rgbkrk

**Comment by SylvainCorlay** [comment]
From discussion with @minrk, the right place to do this is in function `on_message`, to make it check for a whitelist of message type, that would be specified as a configurable on the app type.

https://github.com/jupyter/jupyter_server/blob/master/jupyter_server/services/kernels/handlers.py#L294

**Comment by rgbkrk** [comment]
Neat. When disabled, it would be really nice if there's some amount of feedback that it's being blocked.

* A message (on the protocol) for the UI to consume
* Log attempts to use the blocked message types so that we can
  * find out which app is using the message (maybe erroneously, maybe maliciously)
  * escalate incident response when attempts are being made

**Comment by jasongrout** [comment]
It would also be great if there was a framework to register a message handler, which could possibly transform messages, or hand back a sentinel value that indicates to not deliver the message (and perhaps a separate reply message to send back when applicable, like you suggest with execute_reply). Making the handler configurable makes it easy to experiment with different workflows. For example, @williamstein at one point wanted to intercept display messages to strip out image mimedata to store it in a database and replace the data with a link.

As you indicate, it's probably a lot more code (so maybe not now?), but it's also a lot more flexible in the long run.

**Comment by SylvainCorlay** [comment]
Agreed. `jupyter_server` is a smaller codebase to enable this kind of features than the classic notebook, so we should be able to do this sort of things soone.
