### ISSUE TITLE
[DISCUSS] Should the base.handlers have their counterpart in extension.handlers?

### ISSUE THREAD

**Issue by echarles** [jupyter/jupyter_server#173]
While converting JupyerLab Server to a Server Extension, it has been pretty easy to implement `class LabServerApp(ExtensionAppJinjaMixin, ExtensionApp)`

This works fine without touching the handlers which are still the old classical flavor (not a ExtensionHandler). If we also want to have the handler as pure extension, there are a bunch of code to be duplicated: the `base.handlers.py` (APIHandler...) should be replicated in something like `extensions.base_handler.py`.

Do we want to go this way? Maybe the `base.handlers.py` could extend/reuse the `extensions.base_handler.py`?

**Comment by Zsailer** [comment]
See my comments in #174.

**Comment by echarles** [comment]
This question has been solved making the ExtensionApp a Mixin.

Closing.
