### ISSUE TITLE
Create a `jupyter_server` extension for the classic notebook.

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/jupyter_server#18]
This could be in a `classic_notebook` repository on the jupyter organization, or as a PR on the actual classic notebook (with a greater risk of not being merged).

The `classic_notebook` extension could be a way to enable the classic notebook button with JupyterLab when it is installed on the top of the jupyter_server.

**Comment by SylvainCorlay** [comment]
Following some discussions with @minrk on this. There are two main ways to go with this

1. Create a new `classic_notebook` project which either depends on `notebook` and allows the jupyter server to server the classic notebook JavaScript.
2. Open a PR to the `notebook` repository to make it use the Jupyter server.

The second approach would be more disruptive for the classic notebook repository which is presumably under maintenance mode, but would result in less duplication. Also, it would mean that the classic notebook would need to be updated upon backward incompatible changes in `jupyter_server`... An advantage though would be that PRs improving the current notebook server would apply to `jupyter_server` and won't fall between the cracks.

cc @takluyver @gnestor.

**Comment by blink1073** [comment]
👍 for the second approach, I think it is easier to explain to users as well.

**Comment by Zsailer** [comment]
Here's my experiment—making the classic notebook a jupyter_server extension (using the API from #48). It's so much cleaner! 

https://github.com/Zsailer/notebook_server_extension

@SylvainCorlay — Should I open a the _dracarys_ PR in notebook? 😉

**Comment by Zsailer** [comment]
See [this PR](https://github.com/jupyter/notebook/pull/4653) in the classic notebook.

**Comment by Zsailer** [comment]
Closing for now, since [NBClassic](https://github.com/zsailer/nbclassic) exists.
