### ISSUE TITLE
Drop Travis CI and AppVeyor

### ISSUE THREAD

**Issue by Zsailer** [jupyter/jupyter_server#181]
This was discussed at the last Jupyter Server Meeting.

Github Actions has proved to be a solid, fast option for CI. Thus, it was proposed that we drop Travis and AppVeyor from this project. 

I'm opening this issue to invite others to the discussion. If anyone has any immediate reasons why we should keep Travis and AppVeyor around, let us know. Otherwise, we'll be dropping them at the next Server Meeting.

**Comment by Zsailer** [comment]
See #148. We'll merge this at thursday's meeting!

**Comment by echarles** [comment]
#148 is merge. Closing this..
