### ISSUE TITLE
Doc not in sync

### ISSUE THREAD

**Issue by davidbrochart** [jupyter/jupyter_server#182]
From https://jupyter-server.readthedocs.io/en/stable/frontends.html:
```python
from jupyter_server.extension import ExtensionApp
from jupyter_server.extension import ExtensionHandler
```
Latest stable release is `0.2.1` and it should be:
```python
from jupyter_server.extension.application import ExtensionApp
from jupyter_server.extension.handler import ExtensionHandler
```

From https://jupyter-server.readthedocs.io/en/latest/frontends.html:
```python
from jupyter_server.extension import ExtensionApp
from jupyter_server.extension import ExtensionHandlerMixin
```
From master it should be:
```python
from jupyter_server.extension.application import ExtensionApp
from jupyter_server.extension.handler import ExtensionHandlerMixin
```

**Comment by echarles** [comment]
Thx @davidbrochart for opening this.

The stable doc on readthedocs.io document the stable release 0.2.1 which does not use the mixin. If you build the doc from master, the generated site should be aligned with the master source code.

For the latest on readthedocs.io, I am not sure if it should reflect the master branch an be built on each commit. In that case, we should add the publication in the GitHub actions CI.

**Comment by davidbrochart** [comment]
> The stable doc on readthedocs.io document the stable release 0.2.1 which does not use the mixin.

But it's missing `.application` and `.handler`?

**Comment by echarles** [comment]
Oh I see. Would you mind opening a PR for this? I will merge it.
