### ISSUE TITLE
No browser with file_to_run

### ISSUE THREAD

**Issue by davidbrochart** [jupyter/jupyter_server#189]
Should we allow to not launch a browser even when `file_to_run` is set? Today this is not possible because of https://github.com/jupyter/jupyter_server/blob/master/jupyter_server/serverapp.py#L1822

**Comment by davidbrochart** [comment]
This is needed for Voila, in the case where we have a file to serve but we don't want to launch a browser if launched with `--no-browser`.

**Comment by echarles** [comment]
This makes of sense to me having to serve a file without a browser

**Comment by vidartf** [comment]
Yeah, having a browser pop up if you specify `--no-browser` seems weird.

**Comment by Zsailer** [comment]
Yeah, this makes sense to me. No-browser should always prevent a browser from popping up.
