### ISSUE TITLE
Passing options to multiple jupyter_server extensions

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/jupyter_server#19]
When used on the top of the classic notebook server, the JupyterLab `LabApp` inherits from `NotebookApp` and therefore inherits all of the configuration traits of the classic notbeook, even those that may not be relevant to JupyterLab.

When using `jupyter_server`, both `NotebookApp` and `LabApp` inherit from a common `ServerApp`. Launching `jupyter lab` creates a lab app, and the classic notebook extensions does not see its configuration initialized.

How can we disentangle the server extensions and set options for all of then?

cc @minrk @jasongrout

**Comment by Zsailer** [comment]
I believe this issue is solved by the `ExtensionApp` in #48. Each extension is configurable separately.
