### ISSUE TITLE
[DISCUSS] Release strategy in relation to Kernel Provider

### ISSUE THREAD

**Issue by echarles** [jupyter/jupyter_server#190]
This is a place to summarise the discussion we had during the weekly meeting. We have gone through a few options. My understanding was a that the following got the most support from the participants. Here is my interpretations, please comment/amend:

1. Further work in master in needed to have jupyterlab extension fully operational.
2. Once jupyterlab extension operational, release master as 1.0.0 (stable) on top of which other extensions can be built (voila, ntreact...)
3. Create a maintenance branch 1.x from the 1.0.0 release. That branch goal is to apply any needed fixes reported by the extensions builders. As it is not the goal to apply new feature on that branch, it is likely that master will diverge from branch 1.x.
4. Any new feature will be applied on master branch. This includes the Kernel Provider https://github.com/jupyter/jupyter_server/pull/112. It sounds logical to merge as soon as possible the Kernel Providers in master after release 1.0.0.
5. After release of 1.0.0, branch 1.x can create 1.x releases (1.1.0, 1.2.0...) with fixes. The features committed to master do not have to be back-ported to 1.x.
6. After release of 1.0.0, master will result in a 2.0.0 release once ready with Kernel Provider.

@Zsailer @kevin-bates @vidartf

**Comment by echarles** [comment]
@afshin

**Comment by echarles** [comment]
@davidbrochart

**Comment by echarles** [comment]
I have done more work those last days to get JupyterLab aligned with https://github.com/jupyter/jupyter_server/pull/180

https://dev.azure.com/jupyterlab/jupyterlab/_build/results?buildId=5634 shows green, except for the following steps:

- Linux Doc: Because of https://github.com/jupyterlab/jupyterlab/issues/8068
- Windows JS: While Linux JS succeeds, sometimes Windows JS fails because of... well... you know... windows...?

**Comment by echarles** [comment]
The proposed plan TBD during next weekly meeting:

- Merge https://github.com/Zsailer/jupyter_server/pull/6 in https://github.com/Zsailer/jupyter_server/tree/discover-extensionapp-config (in the meantime I will add in my branch more docs based on experience I had while aligning jlab on the latest server changes)
- Merge https://github.com/Zsailer/jupyter_server/pull/6 in master
- Release 1.0.0 based on master.

**Comment by davidbrochart** [comment]
This release strategy looks good to me. We also need to back-port every bug fix from the 1.x branch to master, that would avoid ending up in the situation we were in in jupyter_client.

**Comment by echarles** [comment]
>  We also need to back-port every bug fix from the 1.x branch to master

+1

**Comment by echarles** [comment]
Closing as https://github.com/jupyter/enhancement-proposals/pull/45 has not been merged.
