### ISSUE TITLE
Create jupyter/jupyter_server gitter room

### ISSUE THREAD

**Issue by echarles** [jupyter/jupyter_server#195]
It would be useful to have a `jupyter/jupyter_server` gitter room to discuss.

**Comment by kevin-bates** [comment]
Thanks for opening this @echarles.

I'm not averse to having a gitter room for quick questions, announcements, and short, chatty kinds of things.  I just find it tough to follow and participate in "discussions" due to its flat nature and it's nearly impossible to find anything from the past.

Might we also want to set up a "category" on the [discussion forum](https://discourse.jupyter.org/)?  I think its ability to have threaded discussions is nicer and more user-friendly.

**Comment by echarles** [comment]
Thx @kevin-bates  I can see also limits with gitter, but find it useful sometimes. I guess the more places where we talk, the more difficult it will be to track down the decisions and find back useful details. I am not personally fan of the forum, but it is a as valid place as gitter.

If needed, we can decide to simply not do it. Let's see what others say.

**Comment by davidbrochart** [comment]
I personally never go to the discourse forum, for me it's between GitHub issues (with none of its advantages) and Gitter. I like Gitter for quick feedback, so that's my preference.

**Comment by echarles** [comment]
I see:

- Gitter for quick and small interactions for urgent or social things (e.g. hey just opened a PR for...)
- GitHub is for things long lasting things that need more discussion than just `hello, how are you`.
- Discourse is for me a downgraded double of GitHub and I try to avoid it.

**Comment by echarles** [comment]
The danger of Gitter is to discuss there things that should be persisted in GitHub.

**Comment by davidbrochart** [comment]
Yes but that we are aware of, and we can open an issue if we think it's worth it.

**Comment by Zsailer** [comment]
Thanks, @echarles, for opening this. 

In my opinion, Gitter, Github, and Discourse serve different personas. 

I think the goal of discourse is to invite a broader range of **users** to the discussion around Jupyter. It's generally a more user-friendly platform than Github. Many users perceive Github as a place for technical conversations only—the Jupyter discourse, instead, is like a "Jupyter StackOverflow" for users.

I think Gitter *should* be a place only for **devs** to discuss real-time work that doesn't need much discussion.

I'm fine with opening a Gitter channel, though I'd prefer not to advertise it on the README. (I want to discourage users from using this channel to ask questions. Those should be directed at Github or Discourse.) Perhaps we can list the gitter badge on the [Server Meeting Issue](https://github.com/jupyter/jupyter_server/issues/126).

**Comment by echarles** [comment]
Discourse sounds more like a better place to be for users. I just wonder what kind of conversation can happen there without the developers. In general (not always) users come with questions/issues that need answers from developers. My personal situation as a developer is that Discourse is a bit too much.

Anyway this was not about Discourse, but about Gitter. Keeping this place a bit more hidden makes sense :+1:

**Comment by Zsailer** [comment]
Looks like we've got a [gitter chat room](https://gitter.im/jupyter/jupyter_server) now!

**Comment by echarles** [comment]
Thx @Zsailer @kevin-bates @lresende
