### ISSUE TITLE
nbconvert<6 ?

### ISSUE THREAD

**Issue by davidbrochart** [jupyter/jupyter_server#198]
Do we still need `nbconvert<6` (https://github.com/jupyter/jupyter_server/blob/master/setup.py#L92). They have released `6.0.0a1` which I'd like to use in https://github.com/voila-dashboards/voila/pull/541.

**Comment by kevin-bates** [comment]
I believe this pin was inherited from Notebook at a time when nbconvert 6 wasn't behaving nicely.  It's since been unpinned in Notebook, so I'm confident we can do the same.

**Comment by Zsailer** [comment]
Fixed in #200. Closing
