### ISSUE TITLE
mean_squared_error function returns wrong values with certain input in Jupyter notebook/

### ISSUE THREAD

**Issue by AntonProkopovich** [jupyter/jupyter_server#20]
I wrote my own function for calculating mean squared error between values of two arrays and it returned wrong values for one particular input (see code below) only . I also tried the same input with built-in MSE function from sklearn.metrics module and the output was the same. It only returns wrong values in Jupyter and works fine in other shells.

Here's the python code and the value 2.99 in the third print line is the one causing the problem:

import numpy as np
from sklearn.metrics import mean_squared_error

print(mean_squared_error(np.array([1, 2, 3]), np.array([0.9, 1.9, 2.9])))
print(mean_squared_error(np.array([1, 2, 3]), np.array([0.98, 1.98, 2.8])))
print(mean_squared_error(np.array([1, 2, 3]), np.array([0.99, 1.99, 2.99])))

**Comment by SylvainCorlay** [comment]
This does not appear to concern jupyter or  jupyter_server. Closing.
