### ISSUE TITLE
load_other_extensions=False in ExtensionApp

### ISSUE THREAD

**Issue by davidbrochart** [jupyter/jupyter_server#211]
I don't understand how an `ExtensionApp` is supposed to work when it has `load_other_extensions=False`. Isn't it going to prevent loading itself also when launched directly?
In the `simple_ext1` example, if you set [this line](https://github.com/jupyter/jupyter_server/blob/8dde7a63c0e99525431df99f7b5d5efaa081eb16/examples/simple/simple_ext1/application.py#L19) to `False`, then `python -m simple_ext1` will show a 404 error in the browser.

**Comment by Zsailer** [comment]
Good catch. This is a bug. 

Looks like this was dropped in #180 by accident. I'll work on a fix + some tests today.
