### ISSUE TITLE
ExtensionApp always open browser

### ISSUE THREAD

**Issue by echarles** [jupyter/jupyter_server#215]
The `open_browser` attribute is always True, whatever we give as trait.

https://github.com/jupyter/jupyter_server/blob/2f02e9353d03e567b00f420070a58a05a30c1407/jupyter_server/extension/application.py#L311-L317

**Comment by echarles** [comment]
@Zsailer  Prolly replacing True with `cls.open_browser` would do the job? If you confirm this should be the way to go, I will open a PR with that change. Thx

**Comment by Zsailer** [comment]
Yeah, this sounds right to me. :+1:

**Comment by Zsailer** [comment]
Merged in #217.

**Comment by michaelaye** [comment]
This is still happening with 1.2.1:
I have the following line in a completely new setup (new .jupyter folder and data folder wiped):

```bash
maye@triton|~/.jupyter 
$ grep open_browser *                                                                                                                                (py38) 
jupyter_server_config.py:c.ServerApp.open_browser = False
```
and when I launch `jupyter lab` a browser window opens.

**Comment by jasongrout** [comment]
Change to `c.ExtensionApp.open_browser = False` - the ExtensionApp default of true is overriding the ServerApp default of false.

**Comment by michaelaye** [comment]
ok, needs to be updated in the docs then, which tells to use ServerApp.open_browser? 
https://jupyter-server.readthedocs.io/en/latest/operators/public-server.html

**Comment by michaelaye** [comment]
`ExtensionApp` isn't part of any of the default generated config files. Where does it need to go? Still to `jupyter_server_config.py` ?

**Comment by Zsailer** [comment]
Actually, 
```
c.ServerApp.open_browser=False
```
only applies you're running jupyter_server directly, i.e.
```
jupyter server
```

To prevent open_browser in Jupyterlab, use the standard way of setting the this trait in jupyterlab,
```
c.LabApp.open_browser=False
```

**Comment by michaelaye** [comment]
it does work though when putting it into the server config like Jason wrote it when launching `jupyter lab`?

**Comment by Zsailer** [comment]
`open_browser` in ServerApp is a different trait than `open_browser` in an extension like JupyterLab. The reason is that the default for `open_browser` in ServerApp is `False` while the default in `LabApp` (or any `ExtensionApp` for that matter) is `True.

**Comment by Zsailer** [comment]
> it does work though when putting it into the server config like Jason wrote it when launching jupyter lab?

It depends on how you're starting the server. 

If you're launching the server using the `jupyter server` entrypoint, then `ServerApp.open_browser=False` will not open a browser.

If you're launching the server using `jupyter lab` entrypoint, then you'll need to use the `LabApp.open_browser=False`, trait.

**Comment by Zsailer** [comment]
And this config should go in `jupyter_lab_config.py`.

**Comment by michaelaye** [comment]
That's not what I see here. I havn no jlab config file, only put `c.ExtensionApp.open_browser=False` into the server config file, and am launching as `jupyter lab` and no browser window opens. (versions all new as of 30 mins ago).

**Comment by Zsailer** [comment]
I see. You're totally right. That will work, but it also means *all* ExtensionApps will inherit this config. For example, running `jupyter nbclassic` will also not open a browser.

**Comment by michaelaye** [comment]
Understood! And it's really great that there's now a more clear separation between config files.
