### ISSUE TITLE
Support windows/python<3.7

### ISSUE THREAD

**Issue by davidbrochart** [jupyter/jupyter_server#239]
We are having the same issue with the `OSError: [WinError 6] The handle is invalid` over in nb_client. It turns out the patch looks quite simple (https://github.com/python/cpython/pull/15706), and it seems that applying it for python<3.7 works (see https://github.com/jupyter/nbclient/pull/77).
Maybe we could also have it in juyter_server and regain compatibility with python3.5 and 3.6 on windows?

**Comment by Zsailer** [comment]
fixed in #240.
