### ISSUE TITLE
Drop ipykernel dependency

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/jupyter_server#254]
`jupyter_server` currently lists ipykernel as a dependency, while it does not really depend on it.

Should we drop ipykernel, to allow people to install a standalone `jupyter_server`? This may be important for people who don't want kernels in their server environment, or who only want to use other language kernels.

**Comment by echarles** [comment]
Why not if current code base does not depend on ipykernel... In that case, extension developers (like jupyterlab) who need it will have to add ipykernel in their dependency list, which is fine and logical.

**Comment by echarles** [comment]
Prolly a check needs to be done to ensure ipykernel was not pulling transitive deps which are needed by jupyter_server
