### ISSUE TITLE
need docs

### ISSUE THREAD

**Issue by minrk** [jupyter/jupyter_server#26]
This repo needs documentation for what it does and how to use it. Right now, it's not clear what starting `jupyter-server` gets you, or how to write an extension (e.g. turn the `notebook` package into an extension of this repo)

**Comment by ProximaDas** [comment]
If nobody is working on this, I can pick it up.

**Comment by blink1073** [comment]
Hi @proximadas, yes, please!

**Comment by Zsailer** [comment]
I'm working on the documentation for server extensions now. Once #48 lands, writing server extensions should be much easier by inheriting from the `ExtensionApp` class. 

I've also begun turning the `notebook` package into a server extension (see jupyter/notebook#4653).

**Comment by willingc** [comment]
@Zsailer @minrk The current docs (https://jupyter-server.readthedocs.io/en/latest/) for this repo are confusing as the title is The Jupyter Notebook which is the same as the notebook docs (https://jupyter-notebook.readthedocs.io/en/stable/). 

Could there be greater distinction between the two? Possibly changing the title for Jupyter-Server docs and also putting a directive at the top of each page that this is not yet a for production project.

**Comment by Zsailer** [comment]
@willingc Embarrassingly, I didn't even know we had a readthedocs page deployed live already.

Thanks for the PR! The docs are terribly behind, but something on the list of things to do soon.
