### ISSUE TITLE
Add maintainers on pypi

### ISSUE THREAD

**Issue by blink1073** [jupyter/jupyter_server#264]
@SylvainCorlay @jasongrout can you please add the following maintainers to https://pypi.org/project/jupyter-server/?

```
datalayer
blink1073
```

Also, can you please make `zsailer` an owner?

**Comment by SylvainCorlay** [comment]
Sure. As soon as I get back to a keyboard.

**Comment by SylvainCorlay** [comment]
Done

**Comment by blink1073** [comment]
Thanks!
