### ISSUE TITLE
Add some missing files to manifest?

### ISSUE THREAD

**Issue by vidartf** [jupyter/jupyter_server#266]
I have previously made a little tool called [`manifix`](https://github.com/vidartf/manifix/) for checking that you haven't missed adding some files to the manifest. Running it on this repo lists these files as possible candidates for inclusion (filtered to files I am unsure about):
```
Extra file: 'jupyter_server\\i18n\\notebook.pot'
Extra file: 'pytest.ini'
Extra file: 'jupyter_server\\i18n\\nbui.pot'
Extra file: 'jupyter_server\\i18n\\nbjs.json'
Extra file: 'CHANGELOG.md'
Extra file: 'jupyter_server\\i18n\\README.md'
Extra file: 'jupyter_server\\i18n\\babel_notebook.cfg'
Extra file: 'jupyter_server\\static\\favicon.ico'
Extra file: 'RELEASE.md'
Extra file: 'jupyter_server\\i18n\\babel_nbui.cfg'
```

I'm guessing some of these are meant to be included?

**Comment by Zsailer** [comment]
Thanks, @vidartf! You're right. Opend #268 to add these files.
