### ISSUE TITLE
jupyter_server sprint

### ISSUE THREAD

**Issue by Zsailer** [jupyter/jupyter_server#27]
Hello @SylvainCorlay and @blink1073!

I talked with @ellisonbg this morning about the `jupyter_server` project. I'm planning to devote full-time sprinting on this project over the next few weeks. Is there a time you both would be available to video chat and discuss the project? Also, is there a different medium to discuss the project (gitter, slack, etc?)

**Comment by blink1073** [comment]
Hi @Zsailer!  I typically use GH issues for discussion, or video chat when higher bandwidth is required.  I am available tomorrow starting at 9am Pacific.

**Comment by blink1073** [comment]
Actually, 8am Pacific, poor mental math ;).

**Comment by Zsailer** [comment]
Great! Tomorrow at 8am works for me too. That would help me get caught up on the conversation :). 

Let's meet [here](https://calpoly.zoom.us/j/626282064), at 8am Pacific

**Comment by blink1073** [comment]
My prior meeting is running a bit late, is 0830 okay?

**Comment by Zsailer** [comment]
Yeah, no rush! See you then

**Comment by blink1073** [comment]
cf https://github.com/jupyter/enhancement-proposals/pull/21

**Comment by blink1073** [comment]
cf https://github.com/jupyter/notebook/pull/3116
