### ISSUE TITLE
Odd logging behavior of JupyterServer

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/jupyter_server#272]
I am using Jupyter Server with JupyterLab mastering and am seeing odd logging behavior, with blocks of empty lines, followed with blocked of yellow empty log lines:

![Screen Shot 2020-08-10 at 6 48 24 PM](https://user-images.githubusercontent.com/27600/89847963-21361500-db3a-11ea-8c5b-57dd7712f4f4.png)

These blocks are repeated throughout the logs, making it difficult to make sense of the logs.

**Comment by echarles** [comment]
Thx @ellisonbg for opening this. I have seen them appear and a few days?weeks before the jupyter server PRs were merged.

The fact that the classname which logs is not reflected in the log line does not help (if LabApp logs, it is shown as ServerApp). I have searched across `jupyterlab`, `jupyterlab-server`, `nbclassic` and `jupyter-server` for a ...log.warn... with potential empty string, but have not find it... 

Those line are not shown on startup. They appear once at the first page request.

Copying @Zsailer who may have ideas on this.

**Comment by echarles** [comment]
When you browse `http://localhost:8888/tree`, the logs are not shown.
When you remove nbclassic shim and browse `http://localhost:8888/lab`, the logs are not shown.

Looks like jupyterlab or jupyterlab_server are generating those logs.

**Comment by Zsailer** [comment]
I'm not sure where this is happening, either. I'll do some investigating today. 

I agree with @echarles—I think we need to verify that the logs reflect the correct log lines. I'll open a separate issue to track that problem.

**Comment by Zsailer** [comment]
This issue was coming from jupyterlab_server. I've submitted a fix in jupyterlab/jupyterlab_server#115.

**Comment by Zsailer** [comment]
Closing, since jupyterlab/jupyterlab_server#115 merged. 🚀

**Comment by echarles** [comment]
Thx a lot for this @Zsailer

**Comment by Zsailer** [comment]
@echarles, #274 should fix the issue with returning the proper classname in the logs.
