### ISSUE TITLE
Static content with base_url

### ISSUE THREAD

**Issue by echarles** [jupyter/jupyter_server#282]
Current behavior when you run with a base_url with `jupyter server --ServerApp.jpserver_extensions="{'simple_ext1': True}" --ServerApp.base_url=/my_prefix`

- Custom handler are served behind `/my_prefix` the http://localhost:8888/my_prefix/simple_ext1/default 
- Static content is not served behind `/my_prefix` http://localhost:8888/static/simple_ext1/home.html 

I can understand static content is nicely segregated by `/static/extension_name/...` but with reverse proxy, deployments typically serve all content (static + dynamic) behind a fixed prefix `/my_prefix` which is not the case here.

Do we keep this like that or do we evolve to `/my_prefix/static/extension_name/...`?
Based on the decision, we will need to fix JupyterLab.

cc/  @Zsailer @blink1073

**Comment by blink1073** [comment]
I agree, `base_url` should always take priority, such as `/myorg/static/lab`, and `/myorg/lab`.

**Comment by Zsailer** [comment]
> I agree, base_url should always take priority, such as /myorg/static/lab, and /myorg/lab.

:+1:

**Comment by echarles** [comment]
This is on the jlab critical path. @Zsailer If the changes are not too difficult, just gimme pointers and I can open a PR. If the changes are large, maybe I will leave it to you if you have time...

**Comment by Zsailer** [comment]
I think it's a simple fix. I'm diving into it now
