### ISSUE TITLE
Busy, terminal... favicons

### ISSUE THREAD

**Issue by echarles** [jupyter/jupyter_server#283]
What iis the place for icons (favicon-busy-1.ico favicon-terminal.ico...) as seen in https://github.com/jupyter/notebook/tree/master/notebook/static/base/images

JupyterLab uses favicon-busy-1.ico. I would be inclined to add them in jupyter_server instead of jupyterlab_server so that other extensions can use them, but happy to hear thoughts on that before opening a PR.

cc/ @Zsailer @blink1073

**Comment by blink1073** [comment]
I agree the onesin `notebook/static/base/images` should be in `jupyter_server`

**Comment by echarles** [comment]
@blink1073 just opened https://github.com/jupyter/jupyter_server/pull/284 to add the favicons in jupyter_server.
