### ISSUE TITLE
Docs review before 1.0.0 release

### ISSUE THREAD

**Issue by echarles** [jupyter/jupyter_server#288]
It is worth reviewing the docs before 1.0.0 release.

**Comment by echarles** [comment]
See e.g. https://github.com/jupyter/jupyter_server/pull/287 to document live reloading.

**Comment by echarles** [comment]
Comments in JupyterLab still points to https://jupyter-notebook.readthedocs.io/en/latest/security.html

This could be replaced with https://jupyter-server.readthedocs.io/en/latest/operators/security.html but the server pages has been logically stripped down to remove notebook specific content.

**Comment by blink1073** [comment]
cf #250 about security upgrades

**Comment by vidartf** [comment]
I see #299 was marked as "contributing" to this, but 1.0.0 is out the door, so is there anything remaining here?

**Comment by echarles** [comment]
I think @Zsailer said he would pass another round on it, but in the meantime jupyter server 1.0.0 has be cut, so yeah it makes sense to close this one. Doing that now. Thx @vidartf
