### ISSUE TITLE
Is there a python lib do the same work as the Kernel.js?

### ISSUE THREAD

**Issue by onewaymyway** [jupyter/jupyter_server#3]
I want to connect remote jupyter_server by python codes rather than in a Browser
but i don't know which lib shall I use
I have checked the jupyter_client lib,but it seems that lib is not what I am looking for,maybe i didn't understand that lib well : )
Is there a python lib that I can use to connect the remote jupyter_server?
I find when it is in a Browser ,Kernel.js do the connect and communicate work
So I wonder is there a python lib can do the same work
Do I have to write a python lib to use websocket to do the same thing as the Kernel.js do or there is already one?
Thanks for your reading!!
I am waiting for answers!!!
: )

**Comment by takluyver** [comment]
[jupyter_client](http://jupyter-client.readthedocs.io/en/latest/api/index.html) is a Python library for starting, stopping and communicating with Jupyter kernels. It interacts with kernels directly over zmq, however, not through the notebook server and websockets. I don't think we have a Python client to talk to kernels over websockets.

**Comment by onewaymyway** [comment]
@takluyver thanks for your answer
It seems I have to write the codes myself!! : )

**Comment by jasongrout** [comment]
If you write such a thing, we're happy to answer questions, and if you want to open source the code, we'd love to see it!

**Comment by parente** [comment]
@onewaymyway https://github.com/jupyter/kernel_gateway_demos/blob/master/python_client_example/src/client.py might be a very rough starting point. It's not a library, but an unrolled example of connecting to a kernel gateway server via a Python client using the Tornado async http client. 

I second what @jasongrout said. If you do work on a Python library that supports talking the Jupyter protocol over websockets, I'd love to see it.

**Comment by takluyver** [comment]
If somebody does tackle this, it would be nice to have a high-level API matching `KernelClient` in jupyter_client, so that it's easy to switch code between using websockets and ZMQ.
