### ISSUE TITLE
Should kernel_info_request be sent on starting and restarting kernel?

### ISSUE THREAD

**Issue by saulshanabrook** [jupyter/jupyter_server#305]
Currently, Jupyter Server [sends a `kernel_info_request` message when restarting a kernel](https://github.com/jupyter/jupyter_server/blob/097676b64cb9043fd65c19d15d4df2fd9d310d50/jupyter_server/services/kernels/kernelmanager.py#L340), but [not when starting a kernel originally](https://github.com/jupyter/jupyter_server/blob/097676b64cb9043fd65c19d15d4df2fd9d310d50/jupyter_server/services/kernels/kernelmanager.py#L152-L196).

As a consequence of this, if you start a kernel through Jupyter Server, and ask for its status, it will always stay in `starting`, because no kernel info requests have been sent yet.

However, if you restart a kernel after starting one, the status will go from `starting`, to `idle`, to `busy`. It will skip `restarting`, I believe due to this bug in Jupyter Client (https://github.com/jupyter/jupyter_server/issues/247 https://github.com/jupyter/jupyter_client/issues/578).

Is it documented the `kernel_info_request` message is sent when restarting a kernel and not for when originally starting a kernel? Is there somewhere with rationale for this behavior?

It was at least unexpected to me that after creating a kernel, the status never became `idle` without having to send a `kernel_info_request` yourself.

**Comment by ellisonbg** [comment]
I would ping @jasongrout as he has spent time looking at aspects of this.

**Comment by kevin-bates** [comment]
Also note that Lab's manual restart behavior differs from that of the Notebook frontend.  

cf. https://github.com/jupyterlab/jupyterlab/pull/8432

**Comment by jasongrout** [comment]
There is corresponding code in this project: https://github.com/jupyter/jupyter_server/blob/097676b64cb9043fd65c19d15d4df2fd9d310d50/jupyter_server/services/kernels/handlers.py#L221

Is there a reason that is not effecting a kernel info request?

**Comment by kevin-bates** [comment]
(Sorry for the delayed response!)
I guess I'm not seeing an issue during startup; status goes to idle following kernel-info-response (running jupyter_server 1.0.5):
```
[D 2020-10-27 06:58:39.799 ServerApp] Starting kernel: ['/opt/anaconda3/envs/elyra2-dev/bin/python3.6', '-m', 'ipykernel_launcher', '-f', '/Users/kbates/Library/Jupyter/runtime/kernel-ea72eca0-6ae3-44cd-9ba1-d33307555263.json']
[D 2020-10-27 06:58:39.805 ServerApp] Connecting to: tcp://127.0.0.1:58851
[D 2020-10-27 06:58:39.806 ServerApp] Connecting to: tcp://127.0.0.1:58848
[I 2020-10-27 06:58:39.808 ServerApp] Kernel started: ea72eca0-6ae3-44cd-9ba1-d33307555263
[D 2020-10-27 06:58:39.809 ServerApp] Kernel args: {'kernel_name': 'python3', 'cwd': '/Users/kbates/notebooks'}
[D 2020-10-27 06:58:39.810 ServerApp] 201 POST /api/sessions?1603807119767 (::1) 19.58ms
[D 2020-10-27 06:58:39.835 ServerApp] Accepting token-authenticated connection from ::1
[D 2020-10-27 06:58:39.836 ServerApp] 200 GET /api/sessions?1603807119828 (::1) 2.41ms
[D 2020-10-27 06:58:39.851 ServerApp] Initializing websocket connection /api/kernels/ea72eca0-6ae3-44cd-9ba1-d33307555263/channels
[D 2020-10-27 06:58:39.854 ServerApp] Requesting kernel info from ea72eca0-6ae3-44cd-9ba1-d33307555263
[D 2020-10-27 06:58:39.854 ServerApp] Connecting to: tcp://127.0.0.1:58847
[D 2020-10-27 06:58:39.857 ServerApp] Accepting token-authenticated connection from ::1
[D 2020-10-27 06:58:39.859 ServerApp] 200 PATCH /api/sessions/0a4c03ce-b301-4395-a5df-e6476968f673?1603807119850 (::1) 2.08ms
[D 2020-10-27 06:58:39.860 ServerApp] Accepting token-authenticated connection from ::1
[D 2020-10-27 06:58:39.862 ServerApp] 200 GET /api/kernels?1603807119853 (::1) 2.32ms
[D 2020-10-27 06:58:39.866 ServerApp] Accepting token-authenticated connection from ::1
[D 2020-10-27 06:58:39.868 ServerApp] 200 PATCH /api/sessions/0a4c03ce-b301-4395-a5df-e6476968f673?1603807119862 (::1) 1.87ms
[D 2020-10-27 06:58:39.873 ServerApp] Accepting token-authenticated connection from ::1
[D 2020-10-27 06:58:39.889 ServerApp] 200 GET /api/kernelspecs?1603807119870 (::1) 16.60ms
[D 2020-10-27 06:58:39.892 ServerApp] Accepting token-authenticated connection from ::1
[D 2020-10-27 06:58:39.894 ServerApp] 200 GET /api/sessions?1603807119877 (::1) 2.63ms
[D 2020-10-27 06:58:40.152 ServerApp] Initializing websocket connection /api/kernels/ea72eca0-6ae3-44cd-9ba1-d33307555263/channels
[D 2020-10-27 06:58:40.154 ServerApp] Waiting for pending kernel_info request
[D 2020-10-27 06:58:40.443 ServerApp] Received kernel info: {'status': 'ok', 'protocol_version': '5.3', 'implementation': 'ipython', 'implementation_version': '7.16.1', 'language_info': {'name': 'python', 'version': '3.6.11', 'mimetype': 'text/x-python', 'codemirror_mode': {'name': 'ipython', 'version': 3}, 'pygments_lexer': 'ipython3', 'nbconvert_exporter': 'python', 'file_extension': '.py'}, 'banner': "Python 3.6.11 | packaged by conda-forge | (default, Aug  5 2020, 20:19:23) \nType 'copyright', 'credits' or 'license' for more information\nIPython 7.16.1 -- An enhanced Interactive Python. Type '?' for help.\n", 'help_links': [{'text': 'Python Reference', 'url': 'https://docs.python.org/3.6'}, {'text': 'IPython Reference', 'url': 'https://ipython.org/documentation.html'}, {'text': 'NumPy Reference', 'url': 'https://docs.scipy.org/doc/numpy/reference/'}, {'text': 'SciPy Reference', 'url': 'https://docs.scipy.org/doc/scipy/reference/'}, {'text': 'Matplotlib Reference', 'url': 'https://matplotlib.org/contents.html'}, {'text': 'SymPy Reference', 'url': 'http://docs.sympy.org/latest/index.html'}, {'text': 'pandas Reference', 'url': 'https://pandas.pydata.org/pandas-docs/stable/'}]}
[D 2020-10-27 06:58:40.444 ServerApp] 101 GET /api/kernels/ea72eca0-6ae3-44cd-9ba1-d33307555263/channels?session_id=582d8d9e-b724-4ba8-815c-93d754443871 (::1) 592.82ms
```
Is this still an issue?

**Comment by saulshanabrook** [comment]
It's more of an internal code question/issue than about the external API. Basically, if you call the `start_kernel` method then the `kernel_info_request` is not sent and the status is not updated. But as @jasongrout pointed about above, the `kernel_info_request` is sent in the `pre_get` method, so I believe if you are hitting the API server you will get the correct responses.

So I can close this.

**Comment by jasongrout** [comment]
Yes, it was also surprising to me, until Min pointed out that `idle` means "done with computation", not "ready for computation": https://jupyter-client.readthedocs.io/en/stable/messaging.html#status

**Comment by kevin-bates** [comment]
I see.  Thank you for your responses.
