### ISSUE TITLE
Services as a trait to the server.

### ISSUE THREAD

**Issue by Zsailer** [jupyter/jupyter_server#31]
Right now, services and their corresponding managers are hardcoded as traits to the `ServerApp`. And the handlers are hardcoded into the web app. 

I think we should make which services are loaded/registered a configurable option. 

This would allow other applications to subclass the `ServerApp` and customize the `services` it uses. I mentioned this briefly in issue #29.

**Comment by Zsailer** [comment]
I'm drafting what a typical service might look like:

```python
services = List(
    dict(
        # Passes manager to tornado settings using this name
    	name='service_name', 
        # Name of the service model to find handlers and manager.
        module='service_module',
        # Name of the manager class to import
        manager='manager_class',
    ),
    ...
)
```

A service module can include the following elements that the ServerApp will look for:
```
my_service
├── __init__.py
├── api_handlers.py
├── handlers.py
└── manager.py
```

**handlers.py**
```python
class MyHandler(JupyterHandler):
    """Handlers for this service."""

handlers = [
    ('url', MyHandler)
]
```
**api_handlers.py**
```python
class MyAPIHandler(APIHandler):
    """API Handlers for this service."""

handlers = [
    ('url', MyAPIHandler)
]
```
**manager.py**
```python
class MyManager(traitlets.config.Configurable):
    """"""
```

**Comment by SylvainCorlay** [comment]
Hey @Zsailer thanks for starting this. I was swamped with work earlier but I am getting into this on Wednesday, review the other PR and edit the JEP!

**Comment by Zsailer** [comment]
Hey @SylvainCorlay, no problem at all! 

I'll move some of these points over to the JEP when I get a chance.

**Comment by Zsailer** [comment]
Closing this issue. I don't think this useful anymore after the Jupyter Server Workshop.
