### ISSUE TITLE
pytest_tornasync becomes hard dependency if pytest is installed

### ISSUE THREAD

**Issue by bollwyvl** [jupyter/jupyter_server#337]
Hey, folks! Hooray for making pytest a first party concern, and offering a pytest plugin :tada:!

Boo for the co-presence of `jupyter_server` and `pytest` making other people's `entry_points` fail :ghost:!

Is there some way that `pytest_tornasync` can be lazily loaded, etc. such that not everything needs to bring it in unless actually testing? 

I mean, I love some `entry_points`, and I would _kill_ for `jupyter_server` extensions to be able to be delivered via "normal means," if indeed `entry_points` were the right way to do it (we some some knock-on effects here), but that software looks a bit long-in-the tooth (which is not necessarily a bad thing, but tornado _has_ changed a fair amount), and I can never quite tell what plugins actually _do_ to my pytest environment.

## Alternatives
- #338: split that file into a separate package (though maybe not _repo_) altogether, e.g. `pytest_jupyter_server`
  - if you install it, because you're going to test (against) `jupyter_server`, it can bring `pytest`, `pytest_tornasync`, etc. along with a proper version pins
- #339: keep the plugin here, but remove the `pytest11` `entry_point`
  - if you're `pytest`ing, you're going to have a `conftest.py`, and it is [read last](https://docs.pytest.org/en/stable/writing_plugins.html#plugin-discovery-order-at-tool-startup), and `pytest_plugins = ["jupyter_server.pytest_plugin"]` isn't that big a lift

The `extras` don't really provide much assurance over time (basically ignored on subsequent solves), and `pytest` (in)compatibility can be a really _real_ thing, even at initialization time. 

> I also _thought_ I read somewhere that the extras wouldn't even be part of some future state of the `pip` solver, but I can't back that up with a link.

related:
- https://github.com/voila-dashboards/voila/issues/728
- https://github.com/krassowski/jupyterlab-lsp/pull/405#discussion_r520543737

**Comment by dhirschfeld** [comment]
Thanks for opening this issue where it actually belongs @bollwyvl!

Over in https://github.com/voila-dashboards/voila/issues/728 @adriendelsalle created a good repro:
https://github.com/voila-dashboards/voila/issues/728#issuecomment-723951109

**Comment by kevin-bates** [comment]
Hi @bollwyvl - thank you for opening this issue along with the helpful information.  I'm sorry things took a couple of months to find their way here and apologize for the frustration this has caused.

@dhirschfeld - thank you for providing the link.

We are currently in the process of addressing a different pytest-related issue (#322) in which we've decided to prefix all of the fixtures we package in a plugin, while moving their definitions to a separate repo: https://github.com/jupyter-server/pytest-jupyter that produces two plugins.  PR #335 is the start of that transition, although based on this information and new understanding, we may want to hasten that effort as we were going to take a multi-step approach so as to not side-effect dependent projects.

The pytest-jupyter plugins have been [published](https://pypi.org/project/pytest-jupyter/) although I suspect they may exhibit a similar issue - so we'll want to focus some of these efforts there.

Let's move any detailed discussion to their respective PRs.

This aspect of pytest (publishing of plugins) is new to us and we were not aware of the negative side-effects.  Sorry again.
