### ISSUE TITLE
traits in notebook that other extensions might depend on

### ISSUE THREAD

**Issue by Zsailer** [jupyter/jupyter_server#35]
After a conversation with @blink1073 this morning,

I looked at traits in `NotebookApp` that other extensions might depend on. If we turn the `NotebookApp` into server extension, such traits/configurations won't be seen by other server extensions. This would break those extensions.

Here is the full list:
```
extra_nbextensions_path
enable_mathjax
max_body_size
max_buffer_size
webapp_settings
server_extensions
nbserver_extensions
notebook_dir
mathjax_url
get_secure_cookie_kwargs
base_project_url
mathjax_config
ignore_minified_js
```

The only trait that causes trouble in JupyterLab is `notebook_dir`. Jupyter server renames this trait to `root_dir`. 

We may want to add `notebook_dir` to jupyter_server with a deprecation warning.

**Comment by krinsman** [comment]
Copy-pasted from my comment on the PR to fix this: 

> Will deprecating and then eventually removing `notebook_dir` make this incompatible with JupyterHub, and thus prevent `jupyter_server` from being used as a backend for `jupyterhub-singleuser`/`SingleUserNotebookApp`?
>
>JupyterHub uses it in a pretty essential way, since that's what `c.Spawner.notebook_dir` hooks into:
https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/spawner.py#L467
https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/spawner.py#L930

**Comment by Zsailer** [comment]
This is handled by the new [shims](https://github.com/Zsailer/nbclassic/pull/7) in [NBClassic](https://github.com/Zsailer/nbclassic). Apps that switch dependency from notebook to jupyter_server should use these shims.
