### ISSUE TITLE
FYI: kernel dies when opening a new Python [conda root] notebook on windows 10 linux subsystem

### ISSUE THREAD

**Issue by lnaie** [jupyter/jupyter_server#4]
Hi,

Got myself to try some ML lessons (http://course.fast.ai/index.html) and I thought it would be handy to do the setup (http://course.fast.ai/lessons/aws.html) of jupyter not on aws but on my windows10 linux subsystem as part of anaconda2 distribution.

After I've opened a new python [conda root] notebook, kernel dies. See the attached screenshot.

![new_python_notebook_kills_jupyter_kernel](https://cloud.githubusercontent.com/assets/1276077/21462898/e0a4c5ec-c961-11e6-82d9-93e327180ae1.png)

Using Anaconda2-4.2.0-Linux-x86_64.sh

**Comment by takluyver** [comment]
It looks like you're using the Ubuntu-on-Windows layer. There have been some issues with that; see jupyter/notebook#1331.
