### ISSUE TITLE
"not implemented" message with jupyter notebook under python-3.8.0a4 (due to switch to "proactor" loop on windows)

### ISSUE THREAD

**Issue by stonebig** [jupyter/jupyter_server#45]
see  https://github.com/jupyter/notebook/issues/4613

maybe Jupyter-Server could be a place to experiment solutions for cheap ?

**Comment by echarles** [comment]
The code has been updated to fix that error. At least tests do not fail on CI (python 3.8 on windows, see https://github.com/jupyter/jupyter_server/blob/master/.github/workflows/main.yml)

**Comment by Zsailer** [comment]
Closing since it looks like the issue was fixed in jupyter_server. If you're still having issues, feel free to reopen.
