### ISSUE TITLE
Support --no-browser

### ISSUE THREAD

**Issue by yuvipanda** [jupyter/jupyter_server#51]
Currently, if you start jupyter server it always starts a browser process. Should support --no-browser that makes this not happen.

**Comment by rolweber** [comment]
Good point. I think that should even be the default behavior, because Jupyter Server without extensions is supposed to be headless.

**Comment by kevin-bates** [comment]
Seems like anything related to starting a browser belongs in the extension and not the server. Could this "browser-related code" be placed into, for example, `ExtensionWebApp` that derives from `ExtensionApp` and from which the likes of Notebook and Lab derive?  Things like Enterprise Gateway - that don't want a browser would derive from `ExtensionApp`.

I understand that's probably easier said than done, but strikes me as the right separation.

**Comment by Zsailer** [comment]
> Should support --no-browser that makes this not happen.

@yuvipanda  Try this:
```
jupyter server --ServerApp.open_browser=False
```
We should make a `--no-browser` alias to simplify this command though.

**Comment by rolweber** [comment]
auto-closed by mistake

**Comment by Zsailer** [comment]
Solved in #82.
