### ISSUE TITLE
Default URL when launching jupyter server puts you in infinite loop

### ISSUE THREAD

**Issue by yuvipanda** [jupyter/jupyter_server#52]
1. Install jupyter_server
2. Run `jupyter server`
3. It opens a URL that's `/?token=XXX` in browser
4. This URL infinitely redirects to itself, never shows anything

If you manually have it open something like `/voila?token=XXX` it works fine. Default behavior should be better.

**Comment by afshin** [comment]
Does this happen **only** in Firefox?

**Comment by yuvipanda** [comment]
@afshin chrome and firefox

**Comment by afshin** [comment]
Cheers!

**Comment by afshin** [comment]
(That is to say, I have no insight.)

**Comment by rolweber** [comment]
Default behavior should be to not open a browser :-) #51

**Comment by yuvipanda** [comment]
@rolweber right, I agree :) However, it does go into an infinite loop even if I specify --ServerApp.open_browser=False, and copy paste the URL manually.

**Comment by rolweber** [comment]
We need to come up with a suitable message for the welcome page.

- _You're looking at the tail end of this headless server._

- _Please move on, there's nothing to see here._

- _Welcome! Please go away._

- _Only robots allowed beyond this point._

**Comment by SylvainCorlay** [comment]
It would make sense to have a tornado template for the a default page (like we have 404.html and 500.html), and have the redirection point to it by default.

- Someone launching `jupyter server` would typically end up at this URL unless they specified something else.
- Someone making explicit use of some ExtensionApp (after @Zsailer's PR is merged) will typically be redirected to the default URL.

**Comment by Zsailer** [comment]
A default page for the server makes the most sense to me.

We should also remove all the notebook templates in this repo.

**Comment by SylvainCorlay** [comment]
> We should also remove all the notebook templates in this repo.

**Comment by Zsailer** [comment]
Solved in #54

**Comment by Zsailer** [comment]
I'm going to close this for now since we added a default landing page in #54. Feel free to re-open if this doesn't fix things for you.
