### ISSUE TITLE
Configure extensions from server CLI.

### ISSUE THREAD

**Issue by Zsailer** [jupyter/jupyter_server#55]
This idea was raised in jupyterlab/jupyterlab#6451. 

**Problem**: the classic notebook can configure both the server and the frontend from the CLI. This is helpful for scenarios where you are deploying jupyter servers from scripts. JupyterHub, for example, launches single-user server using the CLI entry points. Those running notebook or lab as server extensions cannot configure those frontends from the `jupyter server` CLI. 

**Soluton**: I propose we add functionality to Jupyter Server that enables the `jupyter server` CLI to configure extensions (assuming they are configurable objects). This would require `ServerApp` to look for enabled, configurable extensions and dynamically add those classes to the ServerApp's `classes` trait.

**Comment by lresende** [comment]
Could you describe what is the user/consumer experience here? I believe @kevin-bates and I were talking about similar scenario for integrating EG on JupyterServer Phase 2.

**Comment by blink1073** [comment]
For example, passing a spawner argument for JupyterLab in a JupyterHub deployment.  (E.g. static_url if using a cdn).

**Comment by blink1073** [comment]
cf https://jupyterhub.readthedocs.io/en/stable/getting-started/spawners-basics.html

**Comment by blink1073** [comment]
cc @ian-r-rose

**Comment by Zsailer** [comment]
For example, imagine a user launches a jupyter_server with `notebook` and `jupyterlab` extensions enabled. They could configure those extensions from the CLI using:

```
jupyter server \
    --ServerApp.default_url='/lab' \
    --NotebookApp.enable_mathjax=False \
    --LabApp.workspaces_dir='/path/to/workspaces'
```

Any extension that's configurable and enabled could be configured from the CLI.

**Comment by Zsailer** [comment]
> For example, imagine a user launches a jupyter_server with `notebook` and `jupyterlab` extensions enabled. They could configure those extensions from the CLI using:
> 
> ```
> jupyter server \
>     --ServerApp.default_url='/lab' \
>     --NotebookApp.enable_mathjax=False \
>     --LabApp.workspaces_dir='/path/to/workspaces'
> ```
> 
> Any extension that's configurable and enabled could be configured from the CLI.

This works in #180. All CLI arguments are parsed by the ServerApp and stored in a general traitlets `Config` object. For example, the above command will create a config object that looks like:
```python
Config({
    "ServerApp": {
        "default_url": "/lab"
    },
    "NotebookApp: {
        "enable_mathjax: False
    },
    "LabApp": {
        "workspaces_dir": "/path/to/workspace"
    }
})
```
This object is then passed to and shared by all the extensions. Each extension will update it's config with the piece that's relevant to its config.

**Comment by Zsailer** [comment]
This is added in #180 and documented [here](https://jupyter-server.readthedocs.io/en/latest/operators/configuring-extensions.html#extension-config-on-the-command-line).
