### ISSUE TITLE
The readme's link is broken?

### ISSUE THREAD

**Issue by Dustyposa** [jupyter/jupyter_server#57]
Has any docs to know how to use the server? README's link was broken.

**Comment by Zsailer** [comment]
We don't have any docs, yet. The current set of docs are just a fork of Jupyter Notebook's documentation (since this whole repo is really just a fork of jupyter/notebook). 

We'll *hopefully* improve the docs soon, but we're low on available developers...

**Comment by Dustyposa** [comment]
Oh, that's a .....
Has any plane, I want to contribute my own strength.

**Comment by Zsailer** [comment]
We have docs now, building at https://jupyter-server.readthedocs.io.
