### ISSUE TITLE
Fix \s deprecation warning

### ISSUE THREAD

**Issue by vidartf** [jupyter/jupyter_server#591]
## Description

Deprecation warning for regex: invalid escape sequence `\s`

https://github.com/jupyter-server/jupyter_server/blob/1a6a481acb43c34fee201cab80774ab69eab5bb6/jupyter_server/auth/login.py#L112

## Reproduce

Run jupyter_server in a way where you see deprecation warnings.

## Proposed fix

Either escape the backslash, or make the string a raw string by prefixing by r"".

**Comment by Zsailer** [comment]
Thanks, @vidartf. Fixed in #600
