### ISSUE TITLE
Coroutine 'async_replace_file' is not awaited

### ISSUE THREAD

**Issue by Wh1isper** [jupyter/jupyter_server#594]
## Description

https://github.com/jupyter-server/jupyter_server/blob/master/jupyter_server/services/contents/fileio.py#L376

I am currently reading the source code for file operations noticed that it seems to be missing await when call 'async_replace_file'

I'm not sure if this will cause problems

## Context

- Operating System and version:
- Browser and version:
- Jupyter Server version: master(1.12.0.dev0)

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by Wh1isper** [comment]
I created a pr: https://github.com/jupyter-server/jupyter_server/pull/595

It's better to fix it, isn't it? 

:)

**Comment by blink1073** [comment]
Fixed in #595
