### ISSUE TITLE
Drop support for Python 2.7

### ISSUE THREAD

**Issue by rolweber** [jupyter/jupyter_server#63]
Python 2.7 reaches its end of life at new year's eve.
Should we still [bother](https://github.com/jupyter/jupyter_server/pull/62#issuecomment-509954312) with it in jupyter_server until then?

I'm in favor of dropping it rather sooner than later. Should be just some metadata and CI configuration that needs to be updated.

**Comment by kevin-bates** [comment]
This issue was probably written up before the Notebook 6 requirements updates, but since Notebook doesn't support anything less that Python 3.5, I think jupyter_server should follow suit.

I'd be happy to work on this if others are okay with that.
