### ISSUE TITLE
[ExtensionApp] "standalone" mode

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/jupyter_server#64]
I was looking at the extension app mechanism, and I have some thoughts for the `voila` use case.

- Ideally, I would like to have the `voila` command line to become an alias on `jupyter voila`. A byproduct will be that we should be able to drop the `VoilaConfiguration` mixin used by both the tornado application and the server extension...

- Now, one thing about the voila command line that we would lose, is the guarantee that other server extensions are *not* enabled. The reason is that we generally want `voila` to be used to produce standalone web app that don't allow arbitrary code execution. Enabling the `lab` server extension defeats the purpose, because it would provide a means to access and execute code...

- So an idea would be to have a `--standalone` option that only enables the selected server extension and not the other ones. Then `voila` would make use of `jupyter voila --standalone`...

cc @rolweber @Zsailer @epifanio

**Comment by SylvainCorlay** [comment]
Another option would be to have each extension app decide whether they allow other server extensions or not when they are used as the main extension point.

**Comment by rolweber** [comment]
I thought that the selected app is responsible for enabling _all_ extensions that should be running, besides the default stuff that comes with Jupyter Server itself. So if the Voila extension doesn't enable Lab, then Lab isn't there. Am I mistaken there?

**Comment by vidartf** [comment]
> Ideally, I would like to have the voila command line to become an alias on jupyter voila.

Just for context, what is the motivation for this?

**Comment by SylvainCorlay** [comment]
> Just for context, what is the motivation for this?

This would reduce the number of entry points and simplify the codebase (e.g. no need for a VoilaConfiguration object).

**Comment by SylvainCorlay** [comment]
In a way, voila and lab are two perfect examples of extension apps...

**Comment by Zsailer** [comment]
In the current `ExtensionApp` class, VoilaConfiguration already goes away (I desperately need to add documentation to demonstrate this). 

In PR #59, I added logic to handle the extension-specific config. That way, extensions writers don't need to write their own mixin classes (like VoilaConfiguration). 

*How does this work?*

* `ExtensionApp` creates a `Configurable` object to store the extension's trait
* It then passes this object to tornado web-servers settings under the `'<extension_name>_config'` key. 
* If the extensions' handlers inherit the provided `ExtensionHandler` class, this object is accessible under the handler's `self.config` attribute.

**Comment by Zsailer** [comment]
I'm also fine with adding a `--standalone` mode.

**Comment by SylvainCorlay** [comment]
> In the current ExtensionApp class, VoilaConfiguration already goes away (I desperately need to add documentation to demonstrate this).

Yep, but I guess this requires the voila command line to be an alias on `jupyter voila`.

> I'm also fine with adding a `--standalone` mode.

:+1:

**Comment by Zsailer** [comment]
> Yep, but I guess this requires the voila command line to be an alias on jupyter voila.

I think you're right.

You could, instead, have a small subclass that inherits the `Voila` ExtensionApp, changes the `standalone` trait to True, set this trait's tag `config=False`, and add a new `voila` entry-point pointing to this classes `launch_instance` method.

**Comment by Zsailer** [comment]
Adding in #70

**Comment by Zsailer** [comment]
Closing since we added standalone mode in #76.
