### ISSUE TITLE
Release 0.1.0?

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/jupyter_server#65]
Hello everyone. Do you guys see any blocker for a 0.0.6 release of jupyter_server?

That would allow us to move forward with
 - ExtensionApps
 - The ongoing debugger work
 - Some other small fixes that were introduced since 0.0.5

cc @vidartf @Zsailer @epifanio @rolweber

**Comment by Zsailer** [comment]
Would you like me to add a `--standalone` mode first?

**Comment by rolweber** [comment]
Maybe the ExtensionApps merit a version 0.1.0?
Let's not be shy in increasing the version numbers :-)

**Comment by SylvainCorlay** [comment]
> Maybe the ExtensionApps merit a version 0.1.0?

Sure, I think it makes sense. We can start making backward-compatible semver releases then.

**Comment by SylvainCorlay** [comment]
> Would you like me to add a --standalone mode first?

I don't hink we should block on anything. Probably just move forward and don't hesitate to make new releases.

**Comment by Zsailer** [comment]
I think a 0.1.0 release sounds great.

**Comment by SylvainCorlay** [comment]
Tagging and uploading 0.1.0 now!
