### ISSUE TITLE
Access to letsencrypt key files

### ISSUE THREAD

**Issue by jameslao** [jupyter/jupyter_server#67]
I've configured a public server as specified in https://jupyter-notebook.readthedocs.io/en/stable/public_server.html, and I use letsencrypt to generate a key. However, when running the server, it prompts that the private key is not found (understandable, since it requires sudo access). Running jupyter with sudo seems to be discouraged.

If I grant access to my private key to my user, jupyter runs fine, but I can easily view my private key through the command prompt. I understand this is only intended to one user, but having the private key with only the protection of jupyter authentication seems too high a risk. I'm not sure if I'm missing something... Any help would be appreciated.

**Comment by rolweber** [comment]
The kernels will be running with the same user as the Jupyter process. If the Jupyter process has access to a private key, any kernel will also have access to that private key.

You could install a reverse proxy to terminate the TLS connections. Make sure that it supports https as well as wss. The proxy can be running with a different user than Jupyter.

**Comment by jameslao** [comment]
Thanks for the reply. I ended up deploying jupyterhub which can be run as a system service.
