### ISSUE TITLE
Usage of `pathlib.Path.resolve()` breaks symlink trees / forests

### ISSUE THREAD

**Issue by EricCousineau-TRI** [jupyter/jupyter_server#711]
## Description

Unfortunate case of spacebar heating :sweat_smile: 

We have some `bazel` code which runs notebooks.
Bazel works by creating a "runfiles" directory, which contains a series of symlinks from files that may not come from the same directories.

#415 introduced the following logic:
https://github.com/jupyter-server/jupyter_server/blob/55d9f6841b73f15d067a7f1f6979e084310014fb/jupyter_server/serverapp.py#L2542-L2545

However (as a surprise to me), `pathlib.Path.resolve()` will not only make a path absolute, but it will resolve against symlinks.

This is an internal project, but similar code was hoisted to one of our public projects:
https://github.com/RobotLocomotion/drake/tree/v1.0.0/tools/jupyter

## Reproduce

No direct repro script yet; however, I confirmed this will break Bazel out of sandboxes.
If I inject some print statements in this area, I get the following:
```
$ bazel run //:my_jupyter_notebook
...
file_rawpath: /path/to/project/bazel-bin/my_notebook.runfiles/project/my_notebook.ipynb
rootdir_abspath: /bazel/cache/execroot/anzu/bazel-out/k8-opt/bin/my_notebook.runfiles/project
combined_path: /path/to/project/my_notebook.ipynb
...
`root_dir` and `file_to_run` are incompatible. They don't share the same subtrees. Make sure `file_to_run` is on the same path as `root_dir`.
```

## Expected behavior

It should only get **absolute** path, not the **real** path, and it should work fine.

Possible workarounds:

- In our own setup, use `os.path.realpath` on the notebook
  - Feasible, may do this, but would still like to keep *the option* of using `runfiles`
- File PR and wait - better
- Copy all files to the physically same directory - eww
- Monkey patch `serverapp.py` to use `os.path.abspath()` - meh

## Context

- Operating System and version: Ubuntu 20.04
- Browser and version: Firefox 97.0.2
- Jupyter Server version: 1.13.5

<details><summary>Troubleshoot Output</summary>
<pre>
$ bazel run //tools/jupyter:jupyter troubleshoot
...
$PATH:
        {effective venv}
        /usr/local/sbin
        /usr/local/bin
        /usr/sbin
        /usr/bin
        /sbin
        /bin
        /usr/games
        /usr/local/games
        /snap/bin

sys.path:
        {effective venv}
        /usr/lib/python38.zip
        /usr/lib/python3.8
        /usr/lib/python3.8/lib-dynload
        /usr/local/lib/python3.8/dist-packages
        /usr/lib/python3/dist-packages

sys.executable:
        /usr/bin/python3.8

sys.version:
        3.8.10 (default, Nov 26 2021, 20:14:08)
        [GCC 9.3.0]

platform.platform():
        Linux-5.13.0-30-generic-x86_64-with-glibc2.29

which -a jupyter:
        /bazel/cache/execroot/project/bazel-out/k8-opt/bin/external/pip_deps/data/python3.8/bin/jupyter
        /path/to/project/wip/project/bazel-bin/tools/jupyter/jupyter.runfiles/pip_deps/data/python3.8/bin/jupyter
        /usr/bin/jupyter
        /bin/jupyter

pip list:
        Package                  Version
        ------------------------ --------------------
...
        jupyter                  1.0.0
        jupyter-client           7.1.2
        jupyter-console          6.4.3
        jupyter-core             4.9.2
        jupyter-packaging        0.11.1
        jupyter-server           1.13.5
        jupyterlab               3.3.0
        jupyterlab-pygments      0.1.2
        jupyterlab-server        2.10.3
        jupyterlab-widgets       1.0.2
...
</pre>
</details>

<details><summary>Command Line Output</summary>
N/A (I believe)
</details>

<details><summary>Browser Output</summary>
N/A
</details>

**Comment by davidbrochart** [comment]
Thanks for reporting @EricCousineau-TRI.
It looks like using `.absolute()` instead of `.resolve()` would work.

**Comment by EricCousineau-TRI** [comment]
Nice! Didn't see `.absolute()` in the Python docs for some reason, so I guess that's another bug :crying_cat_face: 
Tested in our local setup, and it worked perfectly!

See #712

**Comment by EricCousineau-TRI** [comment]
Ah, was about to file bug report for Python, but looks like it's already fixed in newer (dev) docs:
https://docs.python.org/3.11/library/pathlib.html#id5

> ![image](https://user-images.githubusercontent.com/26719449/157338929-b01f18b6-1f1a-4cc8-a3d4-d23bed79d24f.png)
