### ISSUE TITLE
Cannot load library libgit2

### ISSUE THREAD

**Issue by Lecrapouille** [jupyter/jupyter_server#79]
I'm not 100% sure if I post on the right repo.

I have a ipynb file calling Julia 1.0.x code. I wanted to use my unregistered package so downloading from my GitHub repo with the following code (I'm a newbie with Julia, so yet not sure of the correct code):

```
using Pkg; Pkg.add(PackageSpec(url="https://github.com/xxx/yyy.jl"));
```
On my GitHub page, on https://nbviewer.jupyter.org and on my own jupyter-lab I have the same error (while working perfectly on my Julia 1.0.x):
```
error compiling #add_or_develop#13: error compiling shred!: error compiling #26: error compiling with: error compiling #27: could not load library "libgit2"
/usr/lib/x86_64-linux-gnu/libmbedx509.so.0: undefined symbol: mbedtls_mutex_unlock

Stacktrace:
 [1] #add_or_develop at ./none:0 [inlined]
 [2] #add_or_develop#12 at /build/julia-wJr69F/julia-1.0.3+dfsg/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:29 [inlined]
 [3] #add_or_develop at ./none:0 [inlined]
 [4] #add_or_develop#10 at /build/julia-wJr69F/julia-1.0.3+dfsg/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:27 [inlined]
 [5] #add_or_develop at ./none:0 [inlined]
 [6] #add#18 at /build/julia-wJr69F/julia-1.0.3+dfsg/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:69 [inlined]
 [7] add(::Pkg.Types.PackageSpec) at /build/julia-wJr69F/julia-1.0.3+dfsg/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:69
 [8] top-level scope at In[1]:1
```

It looks like you should include a Julia compiled against the static lib libgit2 but against a shared lib

**Comment by rolweber** [comment]
Hm, no, this isn't the right repo. Jupyter code is written in Python and Typescript. Your problem with Julia in a notebook is about installations of a Julia kernel. 
I suggest that you join the Jupyter Forum at https://discourse.jupyter.org/ and post your question/suggestion in the Q&A section there to get in contact with the people running nbviewer.jupyter.org. For GitHub, you'd have to contact GitHub, but they are probably running some default configuration. There's a chance that changes rolled out to nbviewer.jupyter.org might be picked up by GitHub later.
As for the behavior of your own jupyter-lab installation, that's clearly your own responsibility. If you followed somebody else's instructions for installing the Julia kernel, you might ask whoever provided the instructions.

But if you're doing something that fails everywhere except on your own, non-Jupyter Julia installation, then you might be doing something that just isn't compatible with how the Julia kernel works. In that case, the Jupyter Forum would also be a good place to figure out what's going on and get in contact with people that can help you. Another place to reach out to would be the IJulia kernel community. Their GitHub repo is https://github.com/JuliaLang/IJulia.jl

I'm closing this issue as off-topic.
