### ISSUE TITLE
Porting basic templates from notebook

### ISSUE THREAD

**Issue by Zsailer** [jupyter/jupyter_server#85]
There are various handlers that server basic templates (i.e. login/logout handlers). While Jupyter server doesn't seek to provide a frontend, hitting these handlers results in 500 errors. 

I think we should port basic jinja templates for these handlers that can be overridden or inherited by extensions/subclasses.

**Comment by vidartf** [comment]
Was this resolved in any way by code changes, or closed as "no action"?

**Comment by Zsailer** [comment]
Oops, this was closed by mistake. I misread the issue. Thanks, @vidartf, for catching this.

**Comment by Mistobaan** [comment]
I ended here trying to add the password to my server config file and getting a /login 500 because the html template is missing. There was a file added at some point but seems got lost?

**Comment by Zsailer** [comment]
Fixed in #220. Thanks, @Mistobaan!
