### ISSUE TITLE
Release a new version of jupyter_server

### ISSUE THREAD

**Issue by rolweber** [jupyter/jupyter_server#89]
We should release a new version that includes the security fix from PRs #77 and #88.

**Comment by rolweber** [comment]
@SylvainCorlay You did the last few releases... are you available for another?

If not, who else has the time and knowledge to do a release? Unfortunately, I'm lacking both.

**Comment by kevin-bates** [comment]
I can help with this.  Do we just want @Mseal's changes on top of `0.1.1` or make this comprehensive since `0.1.1`.  I'm assuming we just make this `0.1.2`.

I can't test on Windows, however.

**Comment by SylvainCorlay** [comment]
Hey @rolweber @kevin-bates sorry for the late reply. I can tag a release tomorrow.

Then I will include some release notes in the repository - but it is very boilerplate.

**Comment by Zsailer** [comment]
We successfully synced the classic notebook server with jupyter server (see issue #53 for the full list of PRs we ported). I think we should cut a new release with these changes.

**Comment by Zsailer** [comment]
Pinging @jasongrout and @SylvainCorlay here. Would y'all mind adding me as a maintainer to the jupyter_Server PyPI project, so I can move forward with cutting releases?

**Comment by Zsailer** [comment]
Thanks, @SylvainCorlay! 

I'll work on a new release of Jupyter Server in the next couple of days.

**Comment by Zsailer** [comment]
Closing in favor of #144. We're close to a release!
