### ISSUE TITLE
Adopt native coroutines

### ISSUE THREAD

**Issue by kevin-bates** [jupyter/jupyter_server#93]
Once Python 2 support has been removed (#63), we should update the coroutine decorators and associated backward compatible constructs to use native coroutines (`async def` and `await`).

**Comment by SylvainCorlay** [comment]
There was a massive PR by @blink1073 #23 which did exactly that. At the time, it was decided to not go with this right away to remain closer to the notebook codebase for a little bit longer.

Maybe we want to go ahead with this now.

**Comment by kevin-bates** [comment]
@SylvainCorlay - I'm sorry I didn't catch that - thanks (and thanks @blink1073!)

I think once we've brought over the remaining notebook commits, we should embark on such a thing.  (I suppose we should hold off on #90 until then as well.)  Do we have an enumeration of which commits we should cherry-pick?

**Comment by Zsailer** [comment]
Funny enough, I'm working on the notebook PR porting now...

**Comment by Zsailer** [comment]
These were all updated in #191! :tada: Closing!
